language: minimal

branches:
  only:
    - master

services:
  - docker

script:
  - grep --help
  - docker build --tag elnebuloso/ansible --pull --rm --no-cache --file Dockerfile .
  - export VERSION=$(docker run -it elnebuloso/ansible ansible --version)
#  - export MAJOR=$(docker run -it elnebuloso/ansible ansible --version | grep -e 'ansible \d.\d.\d' | sed 's!ansible !!g' | cut -d. -f1)
#  - export MINOR=$(docker run -it elnebuloso/ansible ansible --version | grep -e 'ansible \d.\d.\d' | sed 's!ansible !!g' | cut -d. -f2)
#  - export PATCH=$(docker run -it elnebuloso/ansible ansible --version | grep -e 'ansible \d.\d.\d' | sed 's!ansible !!g' | cut -d. -f3)
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo ${VERSION}
#  - echo ${MAJOR}
#  - echo ${MINOR}
#  - echo ${PATCH}
#  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}.${MINOR}.${PATCH}
#  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}.${MINOR}
#  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}
#  - docker push elnebuloso/ansible:${MAJOR}.${MINOR}.${PATCH}
#  - docker push elnebuloso/ansible:${MAJOR}.${MINOR}
#  - docker push elnebuloso/ansible:${MAJOR}
#  - docker push elnebuloso/ansible