language: minimal

branches:
  only:
    - master

services:
  - docker

script:
  - version=$(mktemp)
  - docker build --tag elnebuloso/ansible --pull --rm --no-cache --file Dockerfile .
  - docker run -it elnebuloso/ansible ansible --version > ${ansible_version}
  - cat ${version}
  - export MAJOR=$(cat ${version} | grep -Po '(\d+\.\d+\.\d+)' | cut -d. -f1)
  - export MINOR=$(cat ${version} | grep -Po '(\d+\.\d+\.\d+)' | cut -d. -f2)
  - export PATCH=$(cat ${version} | grep -Po '(\d+\.\d+\.\d+)' | cut -d. -f3)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}.${MINOR}.${PATCH}
  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}.${MINOR}
  - docker tag elnebuloso/ansible elnebuloso/ansible:${MAJOR}
  - docker push elnebuloso/ansible:${MAJOR}.${MINOR}.${PATCH}
  - docker push elnebuloso/ansible:${MAJOR}.${MINOR}
  - docker push elnebuloso/ansible:${MAJOR}
  - docker push elnebuloso/ansible