language: minimal

branches:
  only:
    - master

services:
  - docker

script:
  - docker build --tag elnebuloso/ansible --pull --rm --no-cache --file Dockerfile .
  - docker run elnebuloso/ansible ansible --version | grep -Po '^ansible (\\d+\\.)+\\d+' | sed 's!ansible !!g'