FROM centos:centos6
MAINTAINER jeff.tunessen@gmail.com

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

RUN yum clean all \
    && yum -y install epel-release \
    && yum -y install ansible \
    && yum clean all

# sleep infinity, use container as running system you can bash in
CMD ["tail", "-f", "/dev/null"]