FROM centos:centos7
MAINTAINER jeff.tunessen@gmail.com

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

RUN yum clean all \
    && yum -y install epel-release \
    && yum -y install ansible \
    && yum autoremove \
    && yum clean all \

CMD ["sh"]