FROM centos:centos6
MAINTAINER jeff.tunessen@gmail.com

RUN yum -y install epel-release \
    && yum repolist \
    && yum -y install ansible \
    && yum clean all

# sleep infinity, use container as running system for testing ansible roles
CMD ["tail", "-f", "/dev/null"]